---
language: node_js
node_js:
  - "9"

sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/yarn

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - BUILD_STEP=build_and_deploy
  - BUILD_STEP=test
  - BUILD_STEP=lint
  - BUILD_STEP=nsp_check

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add lerna@~2.7.0

install:
  - lerna exec echo "quickly checking for cyclic dependencies" --reject-cycles
  - lerna link
  - yarn install --frozen-lockfile

script:
  - ./ci/$BUILD_STEP.sh

branches:
  only:
    # git-flow branches
    - master
    - production # this is the branch we activate
